const mongoose=require('mongoose')

const carpoolSchema=new mongoose.Schema({
    user:{
      type:mongoose.Schema.Types.ObjectId,
      ref:'User',
      required:true
    },
    wechat:{
      type:String,
      required:true
    },
    departureTime:{
      type:Date,
      required:true
    },
    destination:{
      type:String,
      required:true,
      enum:['nanchang_station','nanchang_south','nanchang_east','nanchang_west','changbei_airport']
    },
    status:{
      type:String,
      default:'active',
      enum:['active','expired','cancelled'] 
    },
    expireAt:{
      type:Date,
      required:true
    },
    //申请
    applicants:[{
      user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
      },
      status:{
        type:String,
        enum:['pending','accepted','rejected'],
        default:'pending'
      }
    }]
},{
  timestamps:true
})
//过滤掉过期的
carpoolSchema.index({expireAt:1},{expireAfterSeconds:0})

module.exports=mongoose.model('Carpool',carpoolSchema)